# Generated by Django 3.0.7 on 2020-07-02 13:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geom', djgeojson.fields.PolygonField()),
            ],
            options={
                'verbose_name_plural': 'incidences',
            },
        ),
    ]
